
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Voice Alauddin</title>
	<meta property="og:url" content="<?php echo current_url() ?>" />
	<meta property="og:site_name" content="Voice Alauddin">
	<meta property="og:image" content="https://yt3.ggpht.com/-zNxBfDmuzEU/AAAAAAAAAAI/AAAAAAAAAAA/2E8-12qlyo4/s800-c-k-no-mo-rj-c0xffffff/photo.jpg" />
	
	<link rel="icon" type="image/png" href="<?php echo base_url() ?>assets/img/valogo.png" >
	<!-- <link rel="icon" type="image/png" href="assets/img/favicons/favicon-16x16.png" sizes="16x16"> -->
	<link rel="manifest" href="assets/img/favicons/manifest.json">
	<meta name="theme-color" content="#ffffff">
	<!-- Normalize -->
	<link rel="stylesheet" type="text/css" href="<?php echo base_url() ?>assets/css/normalize.css">
	<!-- Bootstrap -->
	<link rel="stylesheet" type="text/css" href="<?php echo base_url() ?>assets/css/bootstrap.css">
	<!-- Owl -->
	<link rel="stylesheet" type="text/css" href="<?php echo base_url() ?>assets/css/owl.css">
	<!-- Animate.css -->
	<link rel="stylesheet" type="text/css" href="<?php echo base_url() ?>assets/css/animate.css">
	<!-- Font Awesome -->
	<link rel="stylesheet" type="text/css" href="<?php echo base_url() ?>assets/fonts/font-awesome-4.1.0/css/font-awesome.min.css">
	<!-- Elegant Icons -->
	<link rel="stylesheet" type="text/css" href="<?php echo base_url() ?>assets/fonts/eleganticons/et-icons.css">
	<!-- Main style -->
	<link rel="stylesheet" type="text/css" href="<?php echo base_url() ?>assets/css/cardio.css">
	<link rel="stylesheet" type="text/css" href="<?php echo base_url() ?>assets/css/custom.css">
	<link rel="stylesheet" type="text/css" href="<?php echo base_url() ?>assets/js/slick/slick.css">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Oswald" />
	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[ {
  "@context" : "http://schema.org",
  "@type" : "TVEpisode",
  "partOfTVSeries" : {
    "@type" : "TVSeries",
    "name" : "MAHASISWA KEREN"
  },
  "name" : "Finalis Cantik Sunsilk Hijab Hunt 2018 Berbagi Pengalaman [Part 2]",
  "image" : "https://i.ytimg.com/vi/9EcRxPs_aFo/mqdefault.jpg"
}, {
  "@context" : "http://schema.org",
  "@type" : "TVEpisode",
  "name" : "Finalis Cantik Sunsilk Hijab Hunt 2018 Berbagi Pengalaman [Part 1]",
  "image" : "https://i.ytimg.com/vi/eAN9sg3jMKc/mqdefault.jpg"
}, {
  "@context" : "http://schema.org",
  "@type" : "TVEpisode",
  "name" : "[Part 2] Kisah Inspiratif, Berdakwah Lewat Hijab Syar`i",
  "image" : "https://i.ytimg.com/vi/1hphT5Vte8M/mqdefault.jpg"
}, {
  "@context" : "http://schema.org",
  "@type" : "TVEpisode",
  "name" : "[Part 1] Kisah Inspiratif, Berdakwah Lewat Hijab Syar",
  "image" : "https://i.ytimg.com/vi/6IqEsYKVhi8/mqdefault.jpg"
}, {
  "@context" : "http://schema.org",
  "@type" : "TVEpisode",
  "partOfTVSeries" : {
    "@type" : "TVSeries",
    "name" : "NEWS"
  },
  "name" : "Keren, Menari Massal Mahasiswa UIN Alauddin di Hari Tari Sedunia",
  "image" : "https://i.ytimg.com/vi/OhWvF6LZ0qA/mqdefault.jpg"
}, {
  "@context" : "http://schema.org",
  "@type" : "TVEpisode",
  "name" : "DEMO MAHASISWA ILMU POLITIK, MINTA GEDUNG LAMA FEBI",
  "image" : "https://i.ytimg.com/vi/IsqgaUlYHIY/mqdefault.jpg"
}, {
  "@context" : "http://schema.org",
  "@type" : "TVEpisode",
  "name" : "DI MIWF, AYU UTAMI CERITA KEBURUKAN KARNI ILYAS PRESIDEN ILC",
  "image" : "https://i.ytimg.com/vi/p1YL_YX1Rhk/mqdefault.jpg"
}, {
  "@context" : "http://schema.org",
  "@type" : "TVEpisode",
  "name" : "DEWAN MAHASISWA KITA",
  "image" : "https://i.ytimg.com/vi/9O3NAaMEwyg/mqdefault.jpg"
}, {
  "@context" : "http://schema.org",
  "@type" : "TVEpisode",
  "name" : "MENANTI PRESIDEN MAHASISWA UIN ALAUDDIN 2018",
  "image" : "https://i.ytimg.com/vi/4VMaF9jpLfg/mqdefault.jpg"
} ]
</script>
</head>